version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432"
    ports:
      - '80:8000'
    volumes:
      - ./tests:/opt/tests
      - ./requirements-test.txt:/opt/requirements-test.txt
    depends_on:
      - db

  db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
