apiVersion: apps/v1
kind: Deployment
metadata:
  name: szakdolgozat-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    spec:
      containers:
        - name: szakdoglozat
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8000
          env:
      initContainers:
        - name: migrate-db
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          command: ['flask', 'db', 'upgrade']
          env:
            - name: FLASK_APP
              value: healthcheck_api
---
apiVersion: v1
kind: Service
metadata:
  name: szakdolgozat-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
