apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
commonLabels:
  app: szakdolgozat-github-staging
patches:
  - target:
      kind: Deployment
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: szakdolgozat-github-staging
      - op: add
        path: "/spec/template/spec/containers/0/env"
        value:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: szakdolgozat-shared
                key: db_url_github
  - target:
      kind: Service
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: szakdolgozat-github-staging-service
