on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: szakdolgozat-cluster
  GKE_ZONE: us-west1
  DEPLOYMENT_NAME: szakdolgozat-github-staging
  IMAGE: szakdoglozat-github

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app
        run: |
          docker-compose build app

      - name: Create db
        run: |
          docker-compose up -d db

      - name: Migrate database
        run: |
          docker-compose run app sh -c "flask db upgrade"

      - name: Run tests
        run: |
          docker-compose run app sh -c "pip install -r requirements-test.txt && python -m pytest"

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Publish
        run: |-
          gcloud --quiet auth configure-docker
          docker tag szakdolgozat_2021_app:latest gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
          (cd kubernetes/base && ../../kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA)
          ./kustomize build kubernetes/overlays/github | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
